document.getElementById("header-container").style.backgroundColor = "rgb(25, 255, 144)"
document.getElementsByClassName("emergency-tasks")[0].style.backgroundColor = "rgb(226, 255, 133)"
document.getElementsByClassName("no-emergency-tasks")[0].style.backgroundColor = "rgb(133, 166, 255)"
document.getElementsByTagName("h3")[0].style.backgroundColor = "black"
document.getElementsByTagName("h3")[1].style.backgroundColor = "black"
document.getElementsByTagName("h3")[2].style.backgroundColor = "black"
document.getElementsByTagName("h3")[3].style.backgroundColor = "black"
document.getElementsByTagName('footer')[0].style.backgroundColor = "rgb(77, 79, 84)"